---
# tasks file for roles/rollbacksvc
##################################################
# 1) 방화벽 포트 제거:
# - http
# - https
# 2) 서비스 종료:
# - httpd
# - firewalld
# 3) 웹 서비스 설정 삭제
#- /etc/httpd/conf.d/vhost.conf    
#- /var/www/html/index.html          
#- /var/www/vhosts  
# 4) 패키지 삭제
# - httpd
# - mod_ssl
##################################################

- name: 1) 방화벽 포트 제거
  ansible.posix.firewalld:
    service: "{{ item }}"
    immediate: true
    permanent: true
    state: disabled
  loop: "{{ fw_rules }}"

- name: 2) 서비스 종료
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ svcs }}"


- name: 3) 웹 서비스 설정 파일 삭제
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop: "{{ web_files }}"

- name: 4) 패키지 삭제
  dnf:
    name: "{{ delpack }}"
    state: absent
